import type { SupplierPanelColumn, SupplierPanelDefinition } from "@/features/accounts-payable/suppliers/model"

const text = (key: string, label: string, width?: string): SupplierPanelColumn => ({ key, label, ...(width ? { width } : {}) })
const number = (key: string, label: string, width = "5rem"): SupplierPanelColumn => ({ key, label, width, format: "number" })
const money = (key: string, label: string, width = "6rem"): SupplierPanelColumn => ({ key, label, width, format: "money" })
const date = (key: string, label: string, width = "6rem"): SupplierPanelColumn => ({ key, label, width, format: "date" })
const months = ["january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"] as const
const monthLabels = ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"] as const

export const supplierActionPanels: readonly SupplierPanelDefinition[] = [
  { key: "block-status", label: "Bloquear", title: "Bloqueo del proveedor", section: "actions", path: "actions/block-status", columns: [] },
  { key: "classifications", label: "Clasificar", title: "Selección de parámetros", section: "actions", path: "actions/classifications", columns: [] },
  { key: "discounts", label: "% Descuentos", title: "Descuentos", section: "actions", path: "actions/discounts", columns: [] },
  { key: "events", label: "Eventos", title: "Eventos", section: "actions", path: "actions/events", columns: [date("date", "Fecha"), text("title", "Título", "14rem"), date("followUpAt", "Recordar"), date("dueAt", "Vence"), text("project", "Proyecto", "7rem"), text("requestedBy", "Generó", "7rem")] },
  { key: "various", label: "Varios", title: "Enviar a", section: "actions", path: "actions/various", columns: [] },
  { key: "contacts", label: "Contactos", title: "Contactos", section: "actions", path: "actions/contacts", columns: [text("name", "Nombre", "12rem"), text("position", "Código", "15rem")] },
]

export const supplierQueryPanels: readonly SupplierPanelDefinition[] = [
  { key: "balance", label: "Saldo", title: "Saldo", section: "queries", path: "balance", columns: [number("company", "Mci.", "3rem"), text("document", "Doc.", "6rem"), date("date", "Fecha"), date("dueDate", "Vence"), number("days", "Días", "4rem"), money("originalAmount", "Importe M.N.", "7rem"), money("amount", "Importe", "7rem"), text("currency", "Moneda", "5rem"), text("reference", "Referencia", "8rem"), date("scheduledAt", "Programado"), text("secondaryReference", "Ref.", "7rem"), number("route", "Ruta"), number("exchangeRate", "T.C."), text("folio", "Folio", "6rem")] },
  { key: "movements", label: "Movimientos", title: "Movimientos", section: "queries", path: "movements", columns: [number("company", "Mci.", "3rem"), date("date", "Fecha"), text("document", "Doc.", "6rem"), text("movementType", "T.M.", "4rem"), text("paymentReference", "Referencia", "8rem"), money("amount", "Importe"), number("userId", "Usr", "4rem"), number("exchangeRate", "T.C."), money("exchangeDifference", "D.C."), text("policy", "Póliza", "8rem"), text("documentReference", "Refer piv.", "8rem"), text("currency", "Moneda", "5rem")] },
  { key: "invoices", label: "Facturas", title: "Facturas del mes", section: "queries", path: "invoices", columns: [number("company", "Mcia.", "3rem"), text("document", "Doc.", "6rem"), date("date", "Fecha"), date("dueDate", "Vence"), money("amount", "Importe"), text("reference", "Referencia", "7rem"), text("secondaryReference", "Referencia II", "7rem"), date("paidAt", "Pago"), number("status", "Retraso", "5rem")] },
  { key: "ordered-products", label: "Productos ordenados", title: "Productos ordenados", section: "queries", path: "products/ordered", ct: true, columns: [text("productCode", "Producto", "7rem"), text("description", "Descripción", "18rem"), date("orderDate", "Fecha"), date("expectedAt", "Fecha E."), text("orderNumber", "Núm.", "5rem"), number("orderedQuantity", "Pedido"), number("fulfilledQuantity", "Surtido"), number("remainingQuantity", "Resta"), text("unit", "U.M.", "4rem"), money("price", "Precio"), text("warehouse", "Alm", "4rem"), text("class", "Clase", "4rem"), text("notes", "Obs.", "8rem")] },
  { key: "fill-rate", label: "Fill · Rate", title: "Fill · Rate", section: "queries", path: "fill-rate", columns: [text("orderNumber", "Pedido", "6rem"), text("supplierOrder", "Su Pedido", "7rem"), date("date", "Fecha"), text("source", "Desde", "6rem"), date("dueDate", "Vence"), money("amount", "Importe"), number("fulfilled", "Surtido"), money("gross", "% Surt"), text("status", "Status", "5rem"), text("discount", "Tipo", "5rem")] },
  { key: "quoted-products", label: "Productos cotizados", title: "Productos cotizados", section: "queries", path: "products/quoted", columns: [text("productCode", "Producto", "7rem"), text("description", "Descripción", "18rem"), date("date", "Fecha"), text("quoteNumber", "Núm.", "5rem"), number("quotedQuantity", "Pedido"), number("fulfilledQuantity", "Surtido"), number("remainingQuantity", "Resta"), money("price", "Precio"), text("unit", "U.M.", "4rem")] },
  { key: "purchased-products", label: "Productos comprados", title: "Producto comprados", section: "queries", path: "products/purchased", ct: true, columns: [text("productCode", "Producto", "7rem"), text("description", "Descripción", "18rem"), number("quantity", "Cantidad"), money("amount", "Importe")] },
  { key: "purchased-products-detail", label: "Productos comprados desg.", title: "Producto comprados", section: "queries", path: "products/purchased-detail", columns: [text("productCode", "Producto", "7rem"), text("description", "Descripción", "18rem"), number("quantity", "Cantidad"), money("price", "Precio"), text("document", "Doc.", "6rem"), date("date", "Fecha"), number("pieces", "Pzas")] },
  { key: "price-history", label: "Historial de precios", title: "Historial de precios", section: "queries", path: "products/price-history", columns: [text("productCode", "Producto", "7rem"), text("description", "Descripción", "18rem"), number("quantity", "Cantidad"), money("price", "Precio"), date("date", "Del."), date("date", "Al")] },
  { key: "purchased-expenses", label: "Gastos comprados", title: "Productos comprados", section: "queries", path: "expenses/purchased", columns: [text("expenseCode", "Gasto", "8rem"), text("description", "Descripción", "18rem"), money("amount", "Importe")] },
  { key: "annual-purchases", label: "Compras anuales", title: "Compras Anuales", section: "queries", path: "purchases/annual", columns: [text("productCode", "Código", "7rem"), text("description", "Descripción", "14rem"), number("year", "Año", "4rem"), ...months.map((key, index) => number(key, monthLabels[index], "4rem")), number("total", "Total", "5rem")] },
  { key: "annual-purchases-summary", label: "Compras anuales resumen", title: "Ventas Anuales", section: "queries", path: "purchases/annual-summary", columns: [number("year", "Año", "4rem"), ...months.map((key, index) => money(key, monthLabels[index], "5rem")), money("total", "Total", "6rem")] },
  { key: "work-in-progress", label: "W.I.P.", title: "W.I.P. ALL", section: "queries", path: "work-in-progress", ct: true, columns: [text("productCode", "Producto", "7rem"), text("operation", "Operación", "8rem"), number("requested", "Solicitado"), number("received", "Recibido"), number("remaining", "Resta"), number("time", "Tiempo"), date("start", "Inicio"), text("productionOrder", "O.P.", "7rem"), text("canvas", "Lienzo", "7rem")] },
]
